export const splashLines = [
  'code go brrr',
  'now with extra bugs',
  'terminal juice',
  'building on vibes',
  'one more refactor',
  'slightly less broken than yesterday',
  'ships at 3am',
  'no thoughts, just layouts',
  'probably fine',
  'dangerously optimized',
  'compiling feelings',
  'this is a masterpiece',
  'please do not touch',
  'a small incident',
  'forged in the void',
  'works on my pi',
  'undefined but aesthetic',
  'handcrafted spaghetti',
  'refresh for prophecy',
  'caffeinated pixels',
  'locally sourced chaos',
  'monospace emotional support',
  'prod is a mindset',
  'it compiled so it must be true',
  'frontend incident simulator',
  'css committed a crime',
  'ship first apologize later',
  'one div to rule them all',
  'powered by questionable choices',
  'cache invalidation fan club',
  'works until observed',
  'legally distinct genius',
  'the bug is load-bearing',
  'pixel crimes division',
  'git blame says hello',
  'dependency update survivor',
  'localhost celebrity',
  'typed with unreasonable confidence',
  '404 motivation not found',
  'merge conflict philosopher',
] as const;

export function getSplashLine(index: number) {
  return splashLines[index % splashLines.length];
}
